var goal_data = {
    map: {
        g1: {
            g11: true,
            g12: true,
            g13: true,
            g14: true,
            g15: true,
        },
        g2: {
            g21: true,
            g22: true,
            g23: true,
            g24: true,
            g25: true,
        },
        g3: {
            g31: true,
            g32: true,
            g33: true,
            g34: true,
            g35: true,
        },
        g4: {
            g41: true,
            g42: true,
            g43: true,
            g44: true,
            g45: true,
        },
        g5: {
            g51: true,
            g52: true,
        },

        s1: {
            s11: true,
            s12: true,
            s13: true,
            s14: true,
            s15: true,
        },
        s2: {
            s21: true,
            s22: true,
            s23: true,
            s24: true,
            s25: true,
        },
        s3: {
            s31: true,
            s32: true,
            s33: true,
            s34: true,
            s35: true,
        },
        s4: {
            s41: true,
        },

        m1: {
            m11: true,
            m12: true,
            m13: true,
            m14: true,
            m15: true,
        },
        m2: {
            m21: true,
            m22: true,
            m23: true,
            m24: true,
            m25: true,
        },
        m3: {
            m33: true,
        },

        h1: {
            h11: true,
            h12: true,
            h13: true,
            h14: true,
            h15: true,
        },
        h2: {
            h21: true,
        },

        u1: {
            u11: true,
        },
    },
    g11: {
        title: "It Has Begun",
        reqDisplay: "Purchase 1 Charger.",
        tab: "Main",
        unl() { return true },
        done() { return Decimal.gte(player.upgs[1]||0, 1) },
        progress() { return Decimal.min(player.upgs[1]||0, 1) },
    },
    g12: {
        title: "Energy Acceleration",
        reqDisplay: "Purchase 1 Self-Charging Battery.",
        tab: "Main",
        unl() { return player.goals.includes("g11") },
        done() { return Decimal.gte(player.upgs[2]||0, 1) },
        progress() { return Decimal.min(player.upgs[2]||0, 1) },
    },
    g13: {
        title: "Joule Multiplication",
        reqDisplay: "Purchase 1 Galvanic Compressor.",
        tab: "Main",
        unl() { return player.goals.includes("g12") },
        done() { return Decimal.gte(player.upgs[3]||0, 1) },
        progress() { return Decimal.min(player.upgs[3]||0, 1) },
    },
    g14: {
        title: "Overcharged Field",
        reqDisplay: "Reach an Energy exponent of 10.",
        tab: "Main",
        unl() { return true },
        done() { return tmp.en.exp.gte(10) },
        progress() { return tmp.en.exp.div(10).min(1) },
    },
    g15: {
        title: "Potential Octobyte?",
        reqDisplay: "Reach 1.845e19 Energy.",
        tab: "Main",
        unl() { return true },
        done() { return player.energy.gte(1.845e19) },
        progress() { return player.energy.max(1).log(1.845e19).min(1) },
    },
    g21: {
        title: "All Charged Up!",
        reqDisplay: "Purchase 1 Supercharger.",
        tab: "Main",
        unl() { return player.sup.times.gte(1) },
        done() { return Decimal.gte(player.upgs[4]||0, 1) },
        progress() { return Decimal.min(player.upgs[4]||0, 1) },
    },
    g22: {
        title: "I'm Too Old For This",
        reqDisplay: "Purchase 1 Super Drive.",
        tab: "Main",
        unl() { return player.sup.times.gte(1) },
        done() { return Decimal.gte(player.upgs[5]||0, 1) },
        progress() { return Decimal.min(player.upgs[5]||0, 1) },
    },
    g23: {
        title: "Aging Necessity",
        reqDisplay: "Purchase 1 Archaic Processor.",
        tab: "Main",
        unl() { return player.sup.times.gte(1) },
        done() { return Decimal.gte(player.upgs[6]||0, 1) },
        progress() { return Decimal.min(player.upgs[6]||0, 1) },
    },
    g24: {
        title: "Watt Are You Doing?",
        reqDisplay: "Reach an Energy exponent of 2,500.",
        tab: "Main",
        unl() { return player.sup.times.gte(1) },
        done() { return tmp.en.exp.gte(2.5e3) },
        progress() { return tmp.en.exp.div(2.5e3).min(1) },
    },
    g25: {
        title: "Potential Kilobyte!",
        reqDisplay: "Reach 1.09e2,466 Energy.",
        tab: "Main",
        unl() { return player.sup.times.gte(1) },
        done() { return player.energy.gte("1.09e2466") },
        progress() { return player.energy.max(1).log("1.09e2466").min(1) },
    },
    g31: {
        title: "What Does This Have To Do With Energy?",
        reqDisplay: "Purchase 1 True Soul.",
        tab: "Main",
        unl() { return player.mega.factories.gte(1) },
        done() { return Decimal.gte(player.upgs[7]||0, 1) },
        progress() { return Decimal.min(player.upgs[7]||0, 1) },
    },
    g32: {
        title: "Army of the Heavens",
        reqDisplay: "Purchase 1 Holy Destroyer.",
        tab: "Main",
        unl() { return player.mega.factories.gte(1) },
        done() { return Decimal.gte(player.upgs[8]||0, 1) },
        progress() { return Decimal.min(player.upgs[8]||0, 1) },
    },
    g33: {
        title: "Zap Zap Zap",
        reqDisplay: "Purchase 1 Voltaic Conductor.",
        tab: "Main",
        unl() { return player.mega.factories.gte(1) },
        done() { return Decimal.gte(player.upgs[9]||0, 1) },
        progress() { return Decimal.min(player.upgs[9]||0, 1) },
    },
    g34: {
        title: "Ohm I! You Shouldn't Be Here!",
        reqDisplay: "Reach an Energy exponent of 100,000,000.",
        tab: "Main",
        unl() { return player.mega.factories.gte(1) },
        done() { return tmp.en.exp.gte(1e8) },
        progress() { return tmp.en.exp.max(1).log(1e8).min(1) },
    },
    g35: {
        title: "Potential Megabyte!!",
        reqDisplay: "Reach e2,525,222 Energy.",
        tab: "Main",
        unl() { return player.mega.factories.gte(1) },
        done() { return player.energy.gte("1e2525222") },
        progress() { return player.energy.max(1).log10().max(1).log(2525222).min(1) },
    },
    g41: {
        title: "EnerJerk™",
        reqDisplay: "Purchase 100,000 Self-Charging Batteries.",
        tab: "Main",
        unl() { return player.hyper.times.gte(1) },
        done() { return Decimal.gte(player.upgs[2]||0, 1e5) },
        progress() { return Decimal.div(player.upgs[2]||0, 1e5).min(1) },
    },
    g42: {
        title: "Zap Zap Zap Zap Zap Zap!",
        reqDisplay: "Purchase 56 Voltaic Conductors.",
        tab: "Main",
        unl() { return player.hyper.times.gte(1) },
        done() { return Decimal.gte(player.upgs[9]||0, 56) },
        progress() { return Decimal.div(player.upgs[9]||0, 56).min(1) },
    },
    g43: {
        title: "Sealed Container",
        reqDisplay: "Reduce Energy Overflow to 0.1% of its original power.",
        tab: "Main",
        unl() { return player.hyper.times.gte(1) },
        done() { return tmp.en.overflowPower.lte(.001) },
        progress() { return tmp.en.overflowPower.max(.001).log(.001).min(1) },
    },
    g44: {
        title: "Woah, Stop Getting Me Amped!",
        reqDisplay: "Reach an Energy exponent of 1e15.",
        tab: "Main",
        unl() { return player.hyper.times.gte(1) },
        done() { return tmp.en.exp.gte(1e15) },
        progress() { return tmp.en.exp.max(1).log(1e15).min(1) },
    },
    g45: {
        title: "Potential Petabyte!!!",
        reqDisplay: "Reach e2.711e15 Energy.",
        tab: "Main",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.energy.gte("e2.711e15") },
        progress() { return player.energy.max(1).log10().max(1).log(2.711e15).min(1) },
    },
    g51: {
        title: "Put it into Superdrive?",
        reqDisplay: "Purchase 555 Super Drives.",
        tab: "Main",
        unl() { return player.ultra.times.gte(1) },
        done() { return Decimal.gte(player.upgs[5]||0, 555) },
        progress() { return Decimal.div(player.upgs[5]||0, 555).min(1) },
    },
    g52: {
        title: "Compressed into Nothing",
        reqDisplay: "Get 144,000 extra Galvanic Compressors.",
        tab: "Main",
        unl() { return player.ultra.times.gte(1) },
        done() { return Decimal.gte(tmp.en.upgs[3].extra||0, 144e3) },
        progress() { return Decimal.div(tmp.en.upgs[3].extra||0, 144e3).min(1) },
    },

    s11: {
        title: "It Has Begun (again)",
        reqDisplay: "Perform 2 Super Resets.",
        tab: "Super",
        unl() { return player.sup.times.gte(1) },
        done() { return player.sup.times.gte(2) },
        progress() { return player.sup.times.div(2).min(1) },
    },
    s12: {
        title: "Energy But Worse",
        reqDisplay: "Reach 1e10 Super-Energy.",
        tab: "Super",
        unl() { return player.sup.times.gte(1) },
        done() { return player.sup.energy.gte(1e10) },
        progress() { return player.sup.energy.max(1).log(1e10).min(1) },
    },
    s13: {
        title: "Nice",
        reqDisplay: "Reach a Super-Energy exponent of 69.",
        tab: "Super",
        unl() { return player.unlocks.includes("Super") },
        done() { return tmp.sup.exp.gte(69) },
        progress() { return tmp.sup.exp.div(69).min(1) },
    },
    s14: {
        title: "Agonizing Rock",
        reqDisplay: "Purchase 1 Heroic Stone.",
        tab: "Super",
        unl() { return player.unlocks.includes("Auto") },
        done() { return Decimal.gte(player.sup.upgs[1]||0, 1) },
        progress() { return Decimal.min(player.sup.upgs[1]||0, 1) },
    },
    s15: {
        title: "Artificial Holder",
        reqDisplay: "Purchase 1 Organic Teller.",
        tab: "Super",
        unl() { return player.unlocks.includes("Auto") },
        done() { return Decimal.gte(player.sup.upgs[3]||0, 1) },
        progress() { return Decimal.min(player.sup.upgs[3]||0, 1) },
    },
    s21: {
        title: "Super Maniac",
        reqDisplay: "Perform 10,000 Super Resets.",
        tab: "Super",
        unl() { return player.goals.includes("s11") },
        done() { return player.sup.times.gte(1e4) },
        progress() { return player.sup.times.max(1).log(1e4).min(1) },
    },
    s22: {
        title: "Excitement To The Highest Level",
        reqDisplay: "Reach 1e500 Super-Energy.",
        tab: "Super",
        unl() { return player.mega.factories.gte(1) },
        done() { return player.sup.energy.gte("1e500") },
        progress() { return player.sup.energy.max(1).log("1e500").min(1) },
    },
    s23: {
        title: "Intense Powers",
        reqDisplay: "Reach a Super-Energy exponent of 250.",
        tab: "Super",
        unl() { return player.mega.factories.gte(1) },
        done() { return tmp.sup.exp.gte(250) },
        progress() { return tmp.sup.exp.div(250).min(1) },
    },
    s24: {
        title: "We Did Not Build This City",
        reqDisplay: "Purchase 1 Prestige City.",
        tab: "Super",
        unl() { return player.unlocks.includes("Mega") },
        done() { return Decimal.gte(player.sup.upgs[5]||0, 1) },
        progress() { return Decimal.min(player.sup.upgs[5]||0, 1) },
    },
    s25: {
        title: "What Does This Even Mean???",
        reqDisplay: "Start gaining Supercharged resets passively.",
        tab: "Super",
        unl() { return player.unlocks.includes("Mega") },
        done() { return tmp.auto.superStat.active },
        progress() { return tmp.auto.superStat.active?1:0 },
    },
    s31: {
        title: "Super Destroyer",
        reqDisplay: "Perform 1,000,000 Super Resets.",
        tab: "Super",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.sup.times.gte(1e6) },
        progress() { return player.sup.times.max(1).log(1e6).min(1) },
    },
    s32: {
        title: "Woah This Is Nuts!",
        reqDisplay: "Reach 1e100,000 Super-Energy.",
        tab: "Super",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.sup.energy.gte("1e100000") },
        progress() { return player.sup.energy.max(1).log("1e100000").min(1) },
    },
    s33: {
        title: "Clicking Is Now Useless!",
        reqDisplay: "Reach a Super-Energy exponent of 5,000.",
        tab: "Super",
        unl() { return player.hyper.times.gte(1) },
        done() { return tmp.sup.exp.gte(5e3) },
        progress() { return tmp.sup.exp.div(5e3).min(1) },
    },
    s34: {
        title: "Are We The FBI or Something?",
        reqDisplay: "Purchase 1 Skilled Ninja.",
        tab: "Super",
        unl() { return player.hyper.times.gte(1) },
        done() { return Decimal.gte(player.sup.upgs[9]||0, 1) },
        progress() { return Decimal.min(player.sup.upgs[9]||0, 1) },
    },
    s35: {
        title: "Energy Upgrades Go Brrrrrrrrrr",
        reqDisplay: "Reach a Super-Energy effect of 2,500.",
        tab: "Super",
        unl() { return player.hyper.times.gte(1) },
        done() { return tmp.sup.enEff.gte(2500) },
        progress() { return tmp.sup.enEff.div(2500).min(1) },
    },
    s41: {
        title: "Super Annihilator",
        reqDisplay: "Perform 1e25 Super resets.",
        tab: "Super",
        unl() { return player.ultra.times.gte(1) },
        done() { return player.sup.times.gte(1e25) },
        progress() { return player.sup.times.max(1).log(1e25).min(1) },
    },

    m11: {
        title: "Smoke Billows In The Air",
        reqDisplay: "Reach 3 Mega Factories.",
        tab: "Mega",
        unl() { return player.unlocks.includes("Mega") },
        done() { return player.mega.factories.gte(3) },
        progress() { return player.mega.factories.div(3).min(1) },
    },
    m12: {
        title: "Well Isn't This Familiar...",
        reqDisplay: "Purchase 6 Mega Upgrades.",
        tab: "Mega",
        unl() { return player.unlocks.includes("Mega") },
        done() { return player.mega.upgrades.length>=6 },
        progress() { return Math.min(player.mega.upgrades.length/6, 1) },
    },
    m13: {
        title: "Wow You Died At Level 4? Noob.",
        reqDisplay: "Reach Level 4 in each Skill.",
        tab: "Mega",
        unl() { return player.unlocks.includes("Skills") },
        done() { return tmp.skills[1].lvl.gte(4) && tmp.skills[2].lvl.gte(4) && tmp.skills[3].lvl.gte(4) },
        progress() { return tmp.skills[1].lvl.div(12).min(1/3).plus(tmp.skills[2].lvl.div(12).min(1/3)).plus(tmp.skills[3].lvl.div(12).min(1/3)) },
    },
    m14: {
        title: "Nice^2",
        reqDisplay: "Reach 1e69 Mega-Energy.",
        tab: "Mega",
        unl() { return player.unlocks.includes("Mega") },
        done() { return player.mega.energy.gte(1e69) },
        progress() { return player.mega.energy.max(1).log(1e69).min(1) },
    },
    m15: {
        title: "Owie!",
        reqDisplay: "Reach a Mega-Energy exponent of 100.",
        tab: "Mega",
        unl() { return player.unlocks.includes("Mega") },
        done() { return tmp.mega.exp.gte(100) },
        progress() { return tmp.mega.exp.div(100).min(1) },
    },
    m21: {
        title: "Smoke Billows In The Air",
        reqDisplay: "Reach 50 Mega Factories.",
        tab: "Mega",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.mega.factories.gte(50) },
        progress() { return player.mega.factories.div(50).min(1) },
    },
    m22: {
        title: "This Is All Of Them... Right???",
        reqDisplay: "Purchase 30 Mega Upgrades.",
        tab: "Mega",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.mega.upgrades.length>=30 },
        progress() { return Math.min(player.mega.upgrades.length/30, 1) },
    },
    m23: {
        title: "Still A Noob...",
        reqDisplay: "Reach Level 15 in each Skill.",
        tab: "Mega",
        unl() { return player.hyper.times.gte(1) },
        done() { return tmp.skills[1].lvl.gte(15) && tmp.skills[2].lvl.gte(15) && tmp.skills[3].lvl.gte(15) },
        progress() { return tmp.skills[1].lvl.div(45).min(1/3).plus(tmp.skills[2].lvl.div(45).min(1/3)).plus(tmp.skills[3].lvl.div(45).min(1/3)) },
    },
    m24: {
        title: "Woah That's Some Chad Energy",
        reqDisplay: "Reach 1e500 Mega-Energy.",
        tab: "Mega",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.mega.energy.gte('1e500') },
        progress() { return player.mega.energy.max(1).log('1e500').min(1) },
    },
    m25: {
        title: "Four Twos For Two Fore Tools",
        reqDisplay: "Reach a Mega-Energy exponent of 2,222.",
        tab: "Mega",
        unl() { return player.hyper.times.gte(1) },
        done() { return tmp.mega.exp.gte(2222) },
        progress() { return tmp.mega.exp.div(2222).min(1) },
    },
    m33: {
        title: "Just a noob with time on their hands, right?",
        reqDisplay: "Reach Level 500 in each Skill.",
        tab: "Mega",
        unl() { return player.ultra.times.gte(1) },
        done() { return tmp.skills[1].lvl.gte(500) && tmp.skills[2].lvl.gte(500) && tmp.skills[3].lvl.gte(500) },
        progress() { return tmp.skills[1].lvl.div(1500).min(1/3).plus(tmp.skills[2].lvl.div(1500).min(1/3)).plus(tmp.skills[3].lvl.div(1500).min(1/3)) },
    },

    h11: {
        title: "Nice^3",
        reqDisplay: "Reach 69 Atoms.",
        tab: "Hyper",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.hyper.splitAtoms.gte(69) },
        progress() { return player.hyper.splitAtoms.div(69).min(1) },
    },
    h12: {
        title: "Infinite Power",
        reqDisplay: "Reach 1.8e308 Hyper-Energy.",
        tab: "Hyper",
        unl() { return player.hyper.times.gte(1) },
        done() { return player.hyper.energy.gte("1.8e308") },
        progress() { return player.hyper.energy.max(1).log("1.8e308").min(1) },
    },
    h13: {
        title: "How Unfortunate!",
        reqDisplay: "Reach an Energy exponent of 200,000 within an Unfortunate run.",
        tab: "Hyper",
        unl() { return player.unlocks.includes("Fortune") },
        done() { return player.fortune.furthest.gte(2e5) },
        progress() { return player.fortune.furthest.div(2e5).min(1) },
    },
    h14: {
        title: "RNG Means Nothing!",
        reqDisplay: "Reach 1e6 Gifts.",
        tab: "Hyper",
        unl() { return player.unlocks.includes("Fortune") },
        done() { return player.fortune.gifts.gte(1e6) },
        progress() { return player.fortune.gifts.max(1).log(1e6).min(1) },
    },
    h15: {
        title: "Halfway To Conspiracy",
        reqDisplay: "Reach 3.33e33 Darkness.",
        tab: "Hyper",
        unl() { return player.unlocks.includes("Constellations") },
        done() { return player.constellations.darkness.gte(3.33e33) },
        progress() { return player.constellations.darkness.max(1).log(3.33e33).min(1) },
    },
    h21: {
        title: "Atomic Entropy",
        reqDisplay: "Reach 1.1e11,111 Atoms.",
        tab: "Hyper",
        unl() { return player.unlocks.includes("Ultra") },
        done() { return player.hyper.splitAtoms.gte("1.1e11111") },
        progress() { return player.hyper.splitAtoms.max(1).log("1.1e11111").min(1) },
    },

    u11: {
        title: "Nice^4",
        reqDisplay: "Gain 69.00s of Ultra-Energy in one reset.",
        tab: "Ultra",
        unl() { return player.unlocks.includes("Ultra") },
        done() { return tmp.ultra.gain.gte(69) },
        progress() { return tmp.ultra.gain.div(69).min(1) },
    },
}

var total_goal_count = Object.keys(goal_data).length-1;

function hasGoal(id) {
    return player.goals.includes(id);
}

function updateGoals() {
    for (let i=0;i<Object.keys(goal_data.map).length;i++) for (let j=0;j<Object.keys(Object.values(goal_data.map)[i]).length;j++) {
        let g = Object.keys(Object.values(goal_data.map)[i])[j];
        if (!player.goals.includes(g)) if (goal_data[g].unl()) if (goal_data[g].done()) player.goals.push(g);
    }
}